Repository q9f/eth.rb, pull requests merged in 2022-10, with the labels that each got.

#151 Feature/add http basic support auth
  lib/eth/client.rb
  lib/eth/client/http_basic.rb
  spec/eth/client_spec.rb
Labels: enhancement

#154 eth/client: rename http basic to http auth
  lib/eth/client.rb
  lib/eth/client/http_auth.rb
  spec/eth/client_spec.rb
Labels: refactor

#155 eth/signature: fix allowing ledger v values of 0
  lib/eth/chain.rb
  lib/eth/signature.rb
  spec/eth/chain_spec.rb
  spec/eth/signature_spec.rb
Labels: bug

#157 eth/client: update default fees
  lib/eth/chain.rb
  lib/eth/client.rb
  lib/eth/tx.rb
  spec/eth/client_spec.rb
  spec/eth/tx/eip1559_spec.rb
  spec/eth/tx/eip2930_spec.rb
  spec/eth/tx/legacy_spec.rb
  spec/eth/tx_spec.rb
Labels: enhancement

#159 docs: add readme header for yard
  README.md
Labels: documentation
