Repository q9f/eth.rb, pull requests merged in 2022-06, with the labels that each got.

#111 Include contract constructor args when estimating intrinsic gas
  lib/eth/client.rb
Labels: bug

#112 eth/abi: allow parsing numerics from string inputs
  lib/eth/abi.rb
  spec/eth/abi_spec.rb
Labels: bug

#114 eth/abi: raise error if numeric comes as string
  lib/eth/abi.rb
  spec/eth/abi_spec.rb
Labels: wontfix

#128 Add gas limit override option for contract deployments
  lib/eth/client.rb
  spec/eth/client_spec.rb
Labels: enhancement
