Repository q9f/eth.rb, pull requests merged in 2022-11, with the labels that each got.

#165 gem: bump required ruby version to 3
  .github/workflows/codeql.yml
  .github/workflows/docs.yml
  .github/workflows/spec.yml
  Gemfile
  eth.gemspec
Labels: dependencies

#150 Add ENS resolve support
  abis/ens.json
  eth.gemspec
  lib/eth.rb
  lib/eth/ens/resolver.rb
  spec/eth/ens/resolver_spec.rb
Labels: enhancement

#168 Ability for call contract methods with specific transaction value was added
  lib/eth/client.rb
  spec/eth/client_spec.rb
Labels: enhancement

#169 Ability to manual set nonce of tx for transfer, deploy, transact methods was added.
  lib/eth/client.rb
  spec/eth/client_spec.rb
Labels: enhancement

#170 client: satisfy yard docs for transfer kwargs
  lib/eth/client.rb
Labels: documentation
