Repository q9f/eth.rb, pull requests merged in 2022-12, with the labels that each got.

#175 ci: add libyaml on ubuntu
  .github/workflows/spec.yml
Labels: dependencies, operations

#176 solidity: sanitize the contract path before compiling
  lib/eth/solidity.rb
Labels: bug, operations

#179 eth: happy new 2023
  LICENSE.txt
  lib/eth.rb
  lib/eth/abi.rb
  lib/eth/abi/event.rb
  lib/eth/abi/type.rb
  lib/eth/address.rb
  lib/eth/api.rb
  lib/eth/chain.rb
  lib/eth/client.rb
  lib/eth/client/http.rb
  lib/eth/client/http_auth.rb
  lib/eth/client/ipc.rb
  lib/eth/constant.rb
  lib/eth/contract.rb
  lib/eth/contract/event.rb
  lib/eth/contract/function.rb
  lib/eth/contract/function_input.rb
  lib/eth/contract/function_output.rb
  lib/eth/contract/initializer.rb
  lib/eth/eip712.rb
  lib/eth/ens/resolver.rb
  lib/eth/key.rb
  lib/eth/key/decrypter.rb
  lib/eth/key/encrypter.rb
  lib/eth/rlp.rb
  lib/eth/rlp/decoder.rb
  lib/eth/rlp/encoder.rb
  lib/eth/rlp/sedes.rb
  lib/eth/rlp/sedes/big_endian_int.rb
  lib/eth/rlp/sedes/binary.rb
  lib/eth/rlp/sedes/list.rb
  lib/eth/signature.rb
  lib/eth/solidity.rb
  lib/eth/tx.rb
  lib/eth/tx/eip1559.rb
  lib/eth/tx/eip2930.rb
  lib/eth/tx/legacy.rb
  lib/eth/unit.rb
  lib/eth/util.rb
  lib/eth/version.rb
Labels: documentation

#180 docs: update changelog for 0.5.8
  CHANGELOG.md
  lib/eth/version.rb
  spec/eth_spec.rb
Labels: documentation

#182 eth: rename functions prefixed with is_
  lib/eth/abi.rb
  lib/eth/abi/type.rb
  lib/eth/address.rb
  lib/eth/client.rb
  lib/eth/eip712.rb
  lib/eth/key.rb
  lib/eth/rlp/decoder.rb
  lib/eth/rlp/encoder.rb
  lib/eth/rlp/sedes.rb
  lib/eth/rlp/sedes/binary.rb
  lib/eth/rlp/sedes/list.rb
  lib/eth/signature.rb
  lib/eth/tx.rb
  lib/eth/tx/eip1559.rb
  lib/eth/tx/eip2930.rb
  lib/eth/tx/legacy.rb
  lib/eth/util.rb
  spec/eth/key_spec.rb
  spec/eth/util_spec.rb
Labels: refactor

#173 add `tx_succeeded?`
  lib/eth/client.rb
Labels: enhancement

#172 Support camel case (convert before sending the tx)
  lib/eth/client.rb
Labels: enhancement

#183 eth/client: add test for tx_succeeded?
  lib/eth/client.rb
  spec/eth/client_spec.rb
Labels: spec-tests

#184 eth/client: dup params to prevent marshalling on client obj
  lib/eth/client.rb
  spec/eth/client_spec.rb
Labels: bug

#185 Dynamic struct encoding (#135)
  lib/eth/abi.rb
  lib/eth/abi/type.rb
  lib/eth/client.rb
  lib/eth/contract/function.rb
  lib/eth/contract/function_input.rb
  spec/eth/abi/type_spec.rb
  spec/eth/abi_spec.rb
  spec/eth/contract/function_spec.rb
  spec/eth/contract_spec.rb
  spec/fixtures/abi/Tuple.json
  spec/fixtures/abi/Tuple2.json
  spec/fixtures/contracts/tuple.sol
  spec/fixtures/contracts/tuple2.sol
Labels: enhancement

#186 eth/client: raise an error if a contract interaction reverts
  lib/eth/client.rb
  spec/eth/client_spec.rb
  spec/eth/solidity_spec.rb
  spec/fixtures/contracts/dummy.sol
Labels: enhancement

#188 docs: add coc
  CODE_OF_CONDUCT.md
Labels: documentation

#189 docs: add contribution guidelines
  CONTRIBUTING.md
Labels: documentation

#190 docs: create security policy
  SECURITY.md
Labels: documentation

#191 eth/client: correctly select functions
  .github/workflows/spec.yml
  lib/eth/client.rb
  spec/eth/client_spec.rb
Labels: bug

#194 eth/contract: ensure address arrays support
  spec/eth/contract_spec.rb
  spec/fixtures/contracts/address_storage.sol
Labels: spec-tests

#195 docs: update readme
  README.md
Labels: documentation
