Repository q9f/eth.rb, pull requests merged in 2022-05, with the labels that each got.

#88 Add dependency support for openssl 2.2 and greater, including 3.x (#87)
  eth.gemspec
Labels: dependencies

#89 gem: bump version to 0.5.5
  lib/eth/version.rb
  spec/eth_spec.rb
Labels: operations

#90 docs: update changelog for 0.5.4
  CHANGELOG.md
Labels: documentation

#91 ci: add weekly dependency checks
  .github/dependabot.yml
Labels: dependencies, operations

#96 Add missing def_delegator for constructor_inputs
  lib/eth/contract.rb
Labels: bug

#100 eth/abi: fix handling of hex values for byte strings
  lib/eth/abi.rb
  spec/eth/abi_spec.rb
Labels: bug

#101 eth/abi: add a testcase for handling hex and bin strings
  lib/eth/abi.rb
  spec/eth/abi_spec.rb
Labels: refactor
