Repository q9f/eth.rb, pull requests merged in 2023-01, with the labels that each got.

#197 eth/client: add transfer_erc20 function
  README.md
  lib/eth/client.rb
  spec/eth/client_spec.rb
  spec/fixtures/contracts/deposit.sol
  spec/fixtures/contracts/erc20.sol
Labels: spec-tests

#198 eth/ens: restore docs for normalize
  lib/eth/ens/resolver.rb
Labels: documentation

#200 docs: update changelog for 0.5.10
  CHANGELOG.md
  lib/eth/version.rb
  spec/eth_spec.rb
Labels: documentation

#201 eth/client: rewrite send to send_request
  lib/eth/client.rb
  lib/eth/client/http.rb
  lib/eth/client/http_auth.rb
  lib/eth/client/ipc.rb
Labels: refactor

#202 eth/client: deduplicate code
  lib/eth/client.rb
  lib/eth/client/http.rb
  lib/eth/client/http_auth.rb
  lib/eth/client/ipc.rb
  spec/eth/client_spec.rb
Labels: refactor

#203 eth/abi: split abi class into encoder and decoder
  lib/eth/abi.rb
  lib/eth/abi/decoder.rb
  lib/eth/abi/encoder.rb
  lib/eth/abi/event.rb
  lib/eth/abi/type.rb
  spec/eth/abi/decoder_spec.rb
  spec/eth/abi/encoder_spec.rb
  spec/eth/abi/event_spec.rb
  spec/eth/abi_spec.rb
Labels: refactor

#204 eth/api: update execution apis to latest spec
  lib/eth/api.rb
Labels: operations

#207 Abi.decoder handles arrays of string and bytes
  lib/eth/abi/decoder.rb
  spec/eth/abi_spec.rb
Labels: bug
