Repository q9f/eth.rb, pull requests merged in 2024-06, with the labels that each got.

#269 eth/api: remove coinbase as default account
  .github/workflows/spec.yml
  lib/eth/api.rb
  lib/eth/client.rb
  spec/eth/solidity_spec.rb
Labels: maintenance

#271 ci: update ruby version
  .github/workflows/codeql.yml
  .github/workflows/docs.yml
  .github/workflows/spec.yml
Labels: dependencies, operations, maintenance

#277 gem: run rufo
  lib/eth/abi/decoder.rb
  lib/eth/abi/event.rb
  lib/eth/contract/event.rb
  spec/eth/abi/event_spec.rb
  spec/eth/contract/event_spec.rb
Labels: operations, maintenance

#278 abi/event: confirm decoding tuples works
  spec/eth/abi/event_spec.rb
Labels: spec-tests

#267 Support negative number from JSON RPC
  lib/eth/abi/decoder.rb
  lib/eth/abi/encoder.rb
  spec/eth/abi_spec.rb
Labels: bug

#279 eth/abi: fix negative integer *coding
  lib/eth/abi/encoder.rb
  spec/eth/abi/encoder_spec.rb
  spec/eth/abi_spec.rb
  spec/eth/client_spec.rb
Labels: bug

#280 eth: update version
  CHANGELOG.md
  lib/eth/version.rb
  spec/eth_spec.rb
Labels: maintenance

#281 gem: bump version to 0.5.13
  CHANGELOG.md
  SECURITY.md
  eth.gemspec
  lib/eth/version.rb
  spec/eth_spec.rb
Labels: maintenance
