Repository q9f/eth.rb, pull requests merged in 2025-04, with the labels that each got.

#331 spec/client: fix nonce too low error handling in spec
  spec/eth/client_spec.rb
Labels: spec-tests

#320 Add support for EIP-7702 transactions
  lib/eth/tx.rb
  lib/eth/tx/eip7702.rb
  spec/eth/tx/eip7702_spec.rb
Labels: enhancement

#328 Add ability to decode event parameters using ABI reference.
  lib/eth/contract/event.rb
  spec/eth/contract/event_spec.rb
Labels: enhancement

#332 chore: run rufo, add docs
  lib/eth/abi/event.rb
  lib/eth/address.rb
  lib/eth/chain.rb
  lib/eth/contract/event.rb
  lib/eth/tx.rb
  lib/eth/tx/eip7702.rb
  spec/eth/chain_spec.rb
  spec/eth/contract/event_spec.rb
Labels: documentation
